# Generated by Django 4.1.7 on 2024-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
