# Generated by Django 4.1.7 on 2024-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_url_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_text_field',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
