# Generated by Django 4.1.7 on 2024-03-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_new_text_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_text_field',
            new_name='preview_content',
        ),
    ]
