# Generated by Django 4.1.7 on 2024-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lessonresource_lessonnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonresource',
            name='file',
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
