# Generated by Django 4.1.7 on 2024-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_lessonresource_file_lessonresource_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='linkggformquiz',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
