# Generated by Django 4.1.7 on 2024-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_header_headerandportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerandportfolio',
            name='headers',
            field=models.ManyToManyField(to='myapp.header'),
        ),
    ]
