# Generated by Django 4.1.7 on 2024-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_new_text_field_post_preview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_content',
            field=models.CharField(max_length=1000),
        ),
    ]
