# Generated by Django 4.1.7 on 2024-03-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_headerandportfolio_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeP', models.CharField(choices=[('Card', 'Card'), ('App', 'App'), ('Web', 'Web')], max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='header',
            old_name='subtitle',
            new_name='url',
        ),
        migrations.DeleteModel(
            name='HeaderAndPortfolio',
        ),
    ]
