# Generated by Django 4.1.7 on 2024-03-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='BiBongBenh', max_length=30),
            preserve_default=False,
        ),
    ]
