# Generated by Django 4.1.7 on 2024-03-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_categoryquiz_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='title',
            new_name='nameStore',
        ),
    ]
