# Generated by Django 4.1.7 on 2024-03-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_title_store_namestore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='price',
            new_name='price_000vnd',
        ),
    ]
