# Generated by Django 4.1.7 on 2024-03-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_price_store_price_000vnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='store/'),
        ),
    ]
