# Generated by Django 4.1.7 on 2024-03-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_store_numberstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='numberStore',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
