# Generated by Django 4.1.7 on 2024-03-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_store_numberstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='numberPhone_seller',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
