# Generated by Django 4.1.7 on 2024-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_store_numberphone_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='link_fb_seller',
            field=models.CharField(max_length=100),
        ),
    ]
