# Generated by Django 4.1.7 on 2024-03-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_store_link_fb_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='link_fb_seller',
            new_name='link_conection_seller',
        ),
    ]
