# Generated by Django 4.1.7 on 2024-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_post_is_active_quizquestion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryquiz',
            name='typeCate',
            field=models.CharField(choices=[('TEST ONL', 'TEST ONL'), ('CONTEST', 'CONTEST')], default='TEST ONL', max_length=10),
        ),
    ]
